//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WuQiang.SOA.WebserviceTest.MyWebWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceUser", Namespace="http://schemas.datacontract.org/2004/07/WuQiang.WebSevice.Web.Remote")]
    [System.SerializableAttribute()]
    public partial class WebServiceUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWebWCF.IMyWCF")]
    public interface IMyWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/DoWork", ReplyAction="http://tempuri.org/IMyWCF/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/DoWork", ReplyAction="http://tempuri.org/IMyWCF/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/GetContent", ReplyAction="http://tempuri.org/IMyWCF/GetContentResponse")]
        string GetContent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/GetContent", ReplyAction="http://tempuri.org/IMyWCF/GetContentResponse")]
        System.Threading.Tasks.Task<string> GetContentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/GetUserList", ReplyAction="http://tempuri.org/IMyWCF/GetUserListResponse")]
        System.Collections.Generic.List<WuQiang.SOA.WebserviceTest.MyWebWCF.WebServiceUser> GetUserList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/GetUserList", ReplyAction="http://tempuri.org/IMyWCF/GetUserListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WuQiang.SOA.WebserviceTest.MyWebWCF.WebServiceUser>> GetUserListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyWCFChannel : WuQiang.SOA.WebserviceTest.MyWebWCF.IMyWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWCFClient : System.ServiceModel.ClientBase<WuQiang.SOA.WebserviceTest.MyWebWCF.IMyWCF>, WuQiang.SOA.WebserviceTest.MyWebWCF.IMyWCF {
        
        public MyWCFClient() {
        }
        
        public MyWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string GetContent() {
            return base.Channel.GetContent();
        }
        
        public System.Threading.Tasks.Task<string> GetContentAsync() {
            return base.Channel.GetContentAsync();
        }
        
        public System.Collections.Generic.List<WuQiang.SOA.WebserviceTest.MyWebWCF.WebServiceUser> GetUserList() {
            return base.Channel.GetUserList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WuQiang.SOA.WebserviceTest.MyWebWCF.WebServiceUser>> GetUserListAsync() {
            return base.Channel.GetUserListAsync();
        }
    }
}
